name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build with Parcel
        run: |
          npx parcel build app.js \
            --dist-dir ./dist \
            --no-source-maps \
            --public-url ./

      - name: Clean problematic files
        run: |
          # Remove all symlinks and special files
          find ./dist -type l -delete
          find ./dist -name ".*" -not -name ".nojekyll" -delete
          rm -rf ./dist/.cache ./dist/node_modules

      - name: Verify build output
        run: |
          echo "Build contents:"
          ls -la ./dist
          echo "Total size:"
          du -sh ./dist

      - name: Add required files
        run: |
          touch ./dist/.nojekyll
          [ -f ./dist/index.html ] || echo "<!DOCTYPE html><html><body><script src='app.js'></script></body></html>" > ./dist/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
