name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Matches Parcel v2 requirements

      - name: Install dependencies
        run: npm install

      - name: Build with Parcel
        run: npm run build # This runs "parcel build app.js" from your package.json

      - name: Remove symlinks (Parcel sometimes creates them)
        run: find ./dist -type l -delete

      - name: Add .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
